AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda
Resources:
  TranslateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index
      Runtime: go1.x
      CodeUri: .
      MemorySize: 128
      Timeout: 25
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
                - 'sns:Publish'
                - 'translate:TranslateText'
                - 'comprehend:DetectDominantLanguage'
                - 'cloudwatch:GetMetricStatistics'
              Resource: '*'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
        #GetEvent:
        #  Type: Api
        #  Properties:
        #    Path: /
        #    Method: post